/**
 * Rendering constants for visuals and effects.
 */

export const RENDER_DEPTHS = {
    TERRAIN_GLOW_4: -1,
    TERRAIN_GLOW_3: 0,
    TERRAIN_GLOW_2: 0,
    TERRAIN_GLOW_1: 1,
    TERRAIN_MAIN: 2,
    TANK: 10,
    TRAIL: 17,
    GLOW_OUTER: 18,
    GLOW_MID: 19,
    GLOW_INNER: 20,
    PROJECTILE: 21,
    EXPLOSION: 30,
    FLASH: 40
};

export const COLORS = {
    PLAYER_1: 0x00ffff,
    PLAYER_2: 0xff00ff,
    DEAD: 0x555555,
    PROJECTILE: 0xffffff,
    TRAIL: 0xffffff,
    TERRAIN: 0x00ff00,
    EXPLOSION_OUTER: 0xffaa00,
    EXPLOSION_MID: 0xff5500,
    EXPLOSION_INNER: 0xffffff
};

export const TRAIL_CONFIG = {
    MAX_POINTS: 50, // 20 * 2.5 as requested
    LINE_WIDTH: 2,
    ALPHA: 0.3
};

export const PROJECTILE_VISUALS = {
    MAIN_RADIUS: 3,
    GLOW_INNER_RADIUS: 6,
    GLOW_INNER_ALPHA: 0.4,
    GLOW_MID_RADIUS: 12,
    GLOW_MID_ALPHA: 0.2,
    GLOW_OUTER_RADIUS: 24,
    GLOW_OUTER_ALPHA: 0.1,
    PULSE_BASE: 0.9,
    PULSE_AMPLITUDE: 0.1,
    PULSE_SPEED_DIVISOR: 200,
    PULSE_ALPHA_INNER: 0.6,
    PULSE_ALPHA_MID: 0.3,
    PULSE_ALPHA_OUTER: 0.15
};

export const TANK_VISUALS = {
    BARREL_LENGTH: 20,
    BARREL_WIDTH: 4,
    GLOW_BARREL_WIDTH: 8,
    PULSE_BASE: 0.95,
    PULSE_AMPLITUDE: 0.05,
    PULSE_SPEED_DIVISOR: 400,
    GLOW_INNER_WIDTH: 6,
    GLOW_INNER_ALPHA: 0.3,
    GLOW_MID_WIDTH: 12,
    GLOW_MID_ALPHA: 0.15,
    GLOW_OUTER_WIDTH: 24,
    GLOW_OUTER_ALPHA: 0.05,
    PULSE_INNER_ALPHA_MULT: 0.6,
    PULSE_MID_ALPHA_MULT: 0.3,
    PULSE_OUTER_ALPHA_MULT: 0.15
};

export const TERRAIN_VISUALS = {
    LINE_WIDTH: 2,
    GLOW_1_WIDTH: 4,
    GLOW_1_ALPHA: 0.4,
    GLOW_2_WIDTH: 8,
    GLOW_2_ALPHA: 0.2,
    GLOW_3_WIDTH: 16,
    GLOW_3_ALPHA: 0.1,
    GLOW_4_WIDTH: 32,
    GLOW_4_ALPHA: 0.05,
    PULSE_BASE: 0.9,
    PULSE_AMPLITUDE: 0.1,
    PULSE_SPEED_DIVISOR: 500,
    PULSE_GLOW_1_ALPHA_MULT: 0.6,
    PULSE_GLOW_2_ALPHA_MULT: 0.3,
    PULSE_GLOW_3_ALPHA_MULT: 0.15,
    PULSE_GLOW_4_ALPHA_MULT: 0.07
};

export const EXPLOSION_VISUALS = {
    RING_START_RADIUS: 5,
    OUTER_DURATION: 400,
    OUTER_SCALE: 15,
    OUTER_ALPHA: 0.2,
    MID_DURATION: 300,
    MID_SCALE: 12,
    MID_ALPHA: 0.5,
    INNER_DURATION: 200,
    INNER_SCALE: 8,
    INNER_ALPHA: 0.8,
    PARTICLE_MIN_SPEED: 100,
    PARTICLE_MAX_SPEED: 300,
    PARTICLE_MIN_LIFESPAN: 400,
    PARTICLE_MAX_LIFESPAN: 800,
    PARTICLE_COUNT: 20,
    PARTICLE_DESTROY_DELAY: 1000,
    FLASH_RADIUS: 10,
    FLASH_ALPHA: 0.8,
    FLASH_SCALE: 20,
    FLASH_DURATION: 100
};

export const HUD_CONFIG = {
    DEPTH: 100,
    PLAYER_1_HEX: '#00ffff',
    PLAYER_2_HEX: '#ff00ff',
    TEXT_COLOR: '#ffffff',
    TEXT_COLOR_NUMBER: 0xffffff,
    ACTIVE_COLOR: '#ffff00',
    ACTIVE_COLOR_NUMBER: 0xffff00,
    DEAD_COLOR: '#888888',
    HEALTH_BG_COLOR: 0x333333,
    HEALTH_LOW_COLOR: 0xff0000,
    HEALTH_MID_COLOR: 0xffff00,
    HEALTH_HIGH_COLOR: 0x00ff00,
    BAR_WIDTH: 200,
    BAR_HEIGHT: 12,
    P1_X: 20,
    P2_X: 780,
    Y_START: 20,
    Y_SPACING: 35,
    CENTER_X: 400,
    CENTER_Y: 300,
    STATUS_COLOR: '#ff00ff',
    OVERLAY_COLOR: 0x000000,
    OVERLAY_ALPHA: 0.7,
    FIRE_BTN_BG: '#400',
    FIRE_BTN_COLOR: '#ff4444'
};

export const LOBBY_VISUALS = {
    TITLE_COLOR: '#0f0',
    ERROR_COLOR: '#f00',
    SUCCESS_COLOR: '#0f0'
};
